@startuml SysA
title System Architecture

node "Html client" {
    component ui_front <<index.html>> {
        component media_player <<react component>>
        component cluster <<react component>>
    }
}

node "Spring services" {
    component UIService <<spring service>>
    component MediaService <<spring service>>
    component ClusterService <<spring service>>
}

database MediaDatabase {
}

node "Message Queue Bus" {
    component Kafka <<service>>
}

node "Test Backend" {
  component TestBackendUI <<QT>>
}


media_player -down-> MediaService: RestFul:Media lists\nWebSocket:Audio
cluster -down-> ClusterService: WebSocket

MediaService -left-> MediaDatabase: Media Lists
MediaService -down-> Kafka: Audio\nstates
ClusterService -down-> Kafka: Speed\nPDC\nGear

TestBackendUI -up-> Kafka: Simulate:\nSpeed\nPDC\nGear

@enduml