@startuml SysA
title System Architecture: Component Collaboration

node "Html client" {
    component ui_front <<index.html>> {
        component media_player <<react component>>
        component cluster <<react component>>
    }
}

node "Spring services" {
    component UIService <<spring service>>
    component MediaService <<spring service>>
    component ClusterService <<spring service>>
}

database MediaDatabase <<SQL, MongoDB>>{

}

node "Message Queue Bus" {
    component Kafka <<service>>
}

node "Test Backend" {
  component TestBackendUI <<QT>>
}

media_player -down-> MediaService: RestFul:\nMedia lists
MediaService -up-> media_player: SSE:\nPlayerState\nnotifications

ClusterService -down-> cluster: WebSocket:\nVehicle updates\nSpeed, PDC, Gear

MediaService <-left-> MediaDatabase: SQL or MongoDB:\nMedia Lists
MediaService <-down- Kafka: Consumer:\nPDC
ClusterService <-down- Kafka: Consumer:Speed\nPDC\nGear

TestBackendUI -up-> Kafka: Producer:\nSpeed\nPDC\nGear

@enduml